version: '3.5'

services:

  test-db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'chassis'
      MYSQL_USER: 'chassis'
      MYSQL_PASSWORD: 'password'
    ports:
      - 3309:3306